[graph]
all-features = true

[advisories]
version = 2
ignore = []
yanked = "deny"

[licenses]
version = 2
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BUSL-1.1",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "Zlib",
]
confidence-threshold = 0.8
exceptions = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
