//! Exclusive physical-input lease state machine.

use xenoteer_protocol::{ControlLeaseId, DesktopId};

use super::{GenerationToken, MonotonicMillis, PrincipalId};

/// Release-one controller lease policy.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LeasePolicy {
    default_ttl_ms: u64,
    maximum_ttl_ms: u64,
}

impl LeasePolicy {
    /// Creates a policy whose default and maximum TTL are both non-zero.
    pub fn new(default_ttl_ms: u64, maximum_ttl_ms: u64) -> Result<Self, LeaseError> {
        if default_ttl_ms == 0 || maximum_ttl_ms == 0 || default_ttl_ms > maximum_ttl_ms {
            return Err(LeaseError::InvalidPolicy);
        }
        Ok(Self {
            default_ttl_ms,
            maximum_ttl_ms,
        })
    }

    /// Returns the configured default TTL.
    #[must_use]
    pub const fn default_ttl_ms(self) -> u64 {
        self.default_ttl_ms
    }

    /// Returns the maximum TTL accepted from a caller.
    #[must_use]
    pub const fn maximum_ttl_ms(self) -> u64 {
        self.maximum_ttl_ms
    }

    fn resolve_ttl(self, requested_ttl_ms: Option<u64>) -> Result<u64, LeaseError> {
        let ttl_ms = requested_ttl_ms.unwrap_or(self.default_ttl_ms);
        if ttl_ms == 0 || ttl_ms > self.maximum_ttl_ms {
            return Err(LeaseError::TtlOutOfRange {
                maximum_ms: self.maximum_ttl_ms,
                supplied_ms: ttl_ms,
            });
        }
        Ok(ttl_ms)
    }
}

impl Default for LeasePolicy {
    fn default() -> Self {
        Self {
            default_ttl_ms: 60_000,
            maximum_ttl_ms: 60_000,
        }
    }
}

/// An immutable lease capability returned to its owner.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LeaseGrant {
    /// Opaque lease identifier generated by the caller using a CSPRNG.
    pub lease_id: ControlLeaseId,
    /// Authenticated owner of the capability.
    pub owner: PrincipalId,
    /// Desktop lifetime to which the capability is fenced.
    pub generation: GenerationToken,
    /// Monotonic instant at which the lease becomes invalid.
    pub expires_at: MonotonicMillis,
    /// Most recent admitted owner activity; this never extends `expires_at`.
    pub last_activity_at: MonotonicMillis,
}

/// Why an active lease stopped accepting new physical-input work.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RevocationReason {
    /// The owner explicitly released it.
    Released,
    /// Its TTL elapsed.
    Expired,
    /// A privileged coordinator operation revoked it.
    Revoked,
    /// The desktop generation changed.
    GenerationChanged,
    /// The daemon is shutting down.
    Shutdown,
}

/// Public phase of the lease/reset transaction.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LeasePhase {
    /// No owner exists and a new lease may be acquired.
    Vacant,
    /// One owner may submit physical-input commands.
    Held,
    /// Admission is closed and input cleanup has not started.
    Revoking,
    /// Input cleanup is in progress; a replacement lease remains forbidden.
    Resetting,
}

/// An immutable view of the lease transaction.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LeaseSnapshot {
    /// No lease or cleanup transaction exists.
    Vacant {
        /// Current generation fence.
        generation: GenerationToken,
    },
    /// A lease is active.
    Held(LeaseGrant),
    /// Admission is closed pending reset.
    Revoking {
        /// Lease being revoked.
        lease: LeaseGrant,
        /// Cause of revocation.
        reason: RevocationReason,
    },
    /// Reset has begun and must complete before acquisition.
    Resetting {
        /// Lease whose owned input is being reset.
        lease: LeaseGrant,
        /// Cause of revocation.
        reason: RevocationReason,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum LeaseState {
    Vacant,
    Held(LeaseGrant),
    Revoking {
        lease: LeaseGrant,
        reason: RevocationReason,
    },
    Resetting {
        lease: LeaseGrant,
        reason: RevocationReason,
    },
}

/// Serializes exclusive control and makes lease loss a reset transaction.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LeaseMachine {
    desktop_id: DesktopId,
    generation: GenerationToken,
    policy: LeasePolicy,
    last_observed_at: Option<MonotonicMillis>,
    state: LeaseState,
}

impl LeaseMachine {
    /// Creates a vacant lease machine for the supplied desktop generation.
    pub fn new(
        desktop_id: DesktopId,
        generation: GenerationToken,
        policy: LeasePolicy,
    ) -> Result<Self, LeaseError> {
        if generation.desktop_id() != desktop_id {
            return Err(LeaseError::WrongDesktop);
        }
        Ok(Self {
            desktop_id,
            generation,
            policy,
            last_observed_at: None,
            state: LeaseState::Vacant,
        })
    }

    /// Returns the current phase without exposing holder identity.
    #[must_use]
    pub const fn phase(&self) -> LeasePhase {
        match &self.state {
            LeaseState::Vacant => LeasePhase::Vacant,
            LeaseState::Held(_) => LeasePhase::Held,
            LeaseState::Revoking { .. } => LeasePhase::Revoking,
            LeaseState::Resetting { .. } => LeasePhase::Resetting,
        }
    }

    /// Returns an immutable state snapshot for coordinator-owned publication.
    #[must_use]
    pub fn snapshot(&self) -> LeaseSnapshot {
        match &self.state {
            LeaseState::Vacant => LeaseSnapshot::Vacant {
                generation: self.generation,
            },
            LeaseState::Held(lease) => LeaseSnapshot::Held(lease.clone()),
            LeaseState::Revoking { lease, reason } => LeaseSnapshot::Revoking {
                lease: lease.clone(),
                reason: *reason,
            },
            LeaseState::Resetting { lease, reason } => LeaseSnapshot::Resetting {
                lease: lease.clone(),
                reason: *reason,
            },
        }
    }

    /// Acquires the vacant lease with a caller-generated opaque identifier.
    pub fn acquire(
        &mut self,
        owner: PrincipalId,
        lease_id: ControlLeaseId,
        requested_ttl_ms: Option<u64>,
        now: MonotonicMillis,
        generation: GenerationToken,
    ) -> Result<LeaseGrant, LeaseError> {
        self.validate_generation(generation)?;
        self.observe(now)?;
        self.expire_if_due(now);
        match &self.state {
            LeaseState::Held(lease) => {
                return Err(LeaseError::Occupied {
                    expires_at: lease.expires_at,
                });
            }
            LeaseState::Revoking { .. } | LeaseState::Resetting { .. } => {
                return Err(LeaseError::ResetRequired);
            }
            LeaseState::Vacant => {}
        }

        let ttl_ms = self.policy.resolve_ttl(requested_ttl_ms)?;
        let expires_at = now.checked_add(ttl_ms).ok_or(LeaseError::TimeOverflow)?;
        let grant = LeaseGrant {
            lease_id,
            owner,
            generation,
            expires_at,
            last_activity_at: now,
        };
        self.state = LeaseState::Held(grant.clone());
        Ok(grant)
    }

    /// Renews an unexpired lease after exact owner, ID, and generation checks.
    pub fn renew(
        &mut self,
        owner: &PrincipalId,
        lease_id: ControlLeaseId,
        requested_ttl_ms: Option<u64>,
        now: MonotonicMillis,
        generation: GenerationToken,
    ) -> Result<LeaseGrant, LeaseError> {
        self.validate_generation(generation)?;
        self.observe(now)?;
        if self.expire_if_due(now) {
            return Err(LeaseError::Expired);
        }
        let ttl_ms = self.policy.resolve_ttl(requested_ttl_ms)?;
        let expires_at = now.checked_add(ttl_ms).ok_or(LeaseError::TimeOverflow)?;
        let lease = match &mut self.state {
            LeaseState::Held(lease) => lease,
            LeaseState::Vacant => return Err(LeaseError::NotHeld),
            LeaseState::Revoking { .. } | LeaseState::Resetting { .. } => {
                return Err(LeaseError::ResetRequired);
            }
        };
        Self::validate_capability(lease, owner, lease_id)?;
        lease.expires_at = expires_at;
        lease.last_activity_at = now;
        Ok(lease.clone())
    }

    /// Authorizes activity without implicitly extending the lease TTL.
    pub fn authorize(
        &mut self,
        owner: &PrincipalId,
        lease_id: ControlLeaseId,
        now: MonotonicMillis,
        generation: GenerationToken,
    ) -> Result<LeaseGrant, LeaseError> {
        self.validate_generation(generation)?;
        self.observe(now)?;
        if self.expire_if_due(now) {
            return Err(LeaseError::Expired);
        }
        let lease = match &mut self.state {
            LeaseState::Held(lease) => lease,
            LeaseState::Vacant => return Err(LeaseError::NotHeld),
            LeaseState::Revoking { .. } | LeaseState::Resetting { .. } => {
                return Err(LeaseError::ResetRequired);
            }
        };
        Self::validate_capability(lease, owner, lease_id)?;
        lease.last_activity_at = now;
        Ok(lease.clone())
    }

    /// Begins owner-requested release. Acquisition remains blocked until reset.
    pub fn release(
        &mut self,
        owner: &PrincipalId,
        lease_id: ControlLeaseId,
        now: MonotonicMillis,
        generation: GenerationToken,
    ) -> Result<(), LeaseError> {
        self.validate_generation(generation)?;
        self.observe(now)?;
        if self.expire_if_due(now) {
            return Err(LeaseError::Expired);
        }
        let lease = match &self.state {
            LeaseState::Held(lease) => lease,
            LeaseState::Vacant => return Err(LeaseError::NotHeld),
            LeaseState::Revoking { .. } | LeaseState::Resetting { .. } => {
                return Err(LeaseError::ResetRequired);
            }
        };
        Self::validate_capability(lease, owner, lease_id)?;
        let lease = lease.clone();
        self.state = LeaseState::Revoking {
            lease,
            reason: RevocationReason::Released,
        };
        Ok(())
    }

    /// Revokes an active lease for a coordinator-owned reason.
    ///
    /// Returns `true` if an active lease entered `Revoking`.
    pub fn revoke(&mut self, reason: RevocationReason) -> bool {
        let LeaseState::Held(lease) = &self.state else {
            return false;
        };
        self.state = LeaseState::Revoking {
            lease: lease.clone(),
            reason,
        };
        true
    }

    /// Applies TTL expiry, if due. Expiry never skips the reset transaction.
    pub fn advance_time(&mut self, now: MonotonicMillis) -> Result<bool, LeaseError> {
        self.observe(now)?;
        Ok(self.expire_if_due(now))
    }

    /// Marks the start of conservative owned-input cleanup.
    pub fn begin_reset(&mut self) -> Result<(), LeaseError> {
        let LeaseState::Revoking { lease, reason } = &self.state else {
            return Err(LeaseError::InvalidTransition {
                from: self.phase(),
                operation: "begin_reset",
            });
        };
        self.state = LeaseState::Resetting {
            lease: lease.clone(),
            reason: *reason,
        };
        Ok(())
    }

    /// Completes input cleanup and permits the next acquisition.
    pub fn finish_reset(&mut self) -> Result<(), LeaseError> {
        if !matches!(self.state, LeaseState::Resetting { .. }) {
            return Err(LeaseError::InvalidTransition {
                from: self.phase(),
                operation: "finish_reset",
            });
        }
        self.state = LeaseState::Vacant;
        Ok(())
    }

    /// Applies a new authoritative generation fence.
    ///
    /// An active old-generation lease is revoked. An already-running cleanup
    /// remains mandatory and continues to block acquisition in the new generation.
    pub fn rotate_generation(&mut self, generation: GenerationToken) -> Result<(), LeaseError> {
        if generation.desktop_id() != self.desktop_id {
            return Err(LeaseError::WrongDesktop);
        }
        if generation.epoch() <= self.generation.epoch()
            || generation.generation() == self.generation.generation()
        {
            return Err(LeaseError::StaleGeneration);
        }
        self.generation = generation;
        self.revoke(RevocationReason::GenerationChanged);
        Ok(())
    }

    fn validate_generation(&self, generation: GenerationToken) -> Result<(), LeaseError> {
        if generation.desktop_id() != self.desktop_id {
            return Err(LeaseError::WrongDesktop);
        }
        if generation != self.generation {
            return Err(LeaseError::StaleGeneration);
        }
        Ok(())
    }

    fn observe(&mut self, now: MonotonicMillis) -> Result<(), LeaseError> {
        if self.last_observed_at.is_some_and(|previous| now < previous) {
            return Err(LeaseError::ClockRegressed);
        }
        self.last_observed_at = Some(now);
        Ok(())
    }

    fn expire_if_due(&mut self, now: MonotonicMillis) -> bool {
        let LeaseState::Held(lease) = &self.state else {
            return false;
        };
        if now < lease.expires_at {
            return false;
        }
        self.state = LeaseState::Revoking {
            lease: lease.clone(),
            reason: RevocationReason::Expired,
        };
        true
    }

    fn validate_capability(
        lease: &LeaseGrant,
        owner: &PrincipalId,
        lease_id: ControlLeaseId,
    ) -> Result<(), LeaseError> {
        if &lease.owner != owner {
            return Err(LeaseError::WrongOwner);
        }
        if lease.lease_id != lease_id {
            return Err(LeaseError::WrongLease);
        }
        Ok(())
    }
}

/// A lease state-machine failure.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum LeaseError {
    /// The configured default/maximum TTL relationship is invalid.
    #[error("lease policy requires 0 < default TTL <= maximum TTL")]
    InvalidPolicy,
    /// The requested TTL is zero or exceeds policy.
    #[error("lease TTL {supplied_ms}ms is outside 1..={maximum_ms}ms")]
    TtlOutOfRange {
        /// Maximum permitted TTL.
        maximum_ms: u64,
        /// Caller-supplied TTL.
        supplied_ms: u64,
    },
    /// A lease is already held; holder identity is intentionally omitted.
    #[error("control lease is occupied")]
    Occupied {
        /// Current expiry, safe to expose without holder identity.
        expires_at: MonotonicMillis,
    },
    /// The capability owner does not match the authenticated principal.
    #[error("control lease belongs to another principal")]
    WrongOwner,
    /// The opaque lease identifier did not match.
    #[error("control lease identifier does not match")]
    WrongLease,
    /// No active lease exists.
    #[error("control lease is not held")]
    NotHeld,
    /// The lease expired and cleanup is now required.
    #[error("control lease expired; input reset is required")]
    Expired,
    /// Cleanup must complete before this operation can proceed.
    #[error("input reset must complete before control can be acquired")]
    ResetRequired,
    /// A generation token belongs to a different desktop.
    #[error("generation token belongs to another desktop")]
    WrongDesktop,
    /// A generation token is not the authoritative current token.
    #[error("generation token is stale")]
    StaleGeneration,
    /// A monotonic clock reading moved backwards.
    #[error("monotonic clock regressed")]
    ClockRegressed,
    /// An expiry instant could not be represented.
    #[error("lease expiry overflowed monotonic time")]
    TimeOverflow,
    /// The requested operation violates the reset transaction order.
    #[error("operation {operation} is invalid from phase {from:?}")]
    InvalidTransition {
        /// Current phase.
        from: LeasePhase,
        /// Attempted operation.
        operation: &'static str,
    },
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::coordinator::GenerationFence;
    use xenoteer_protocol::DesktopGeneration;

    fn principal(value: &str) -> Result<PrincipalId, Box<dyn std::error::Error>> {
        Ok(PrincipalId::new(value)?)
    }

    #[test]
    fn expiry_requires_reset_before_reacquisition() -> Result<(), Box<dyn std::error::Error>> {
        let desktop_id = DesktopId::new();
        let fence = GenerationFence::new(desktop_id, DesktopGeneration::new());
        let token = fence.capture();
        let mut leases = LeaseMachine::new(desktop_id, token, LeasePolicy::default())?;
        let owner = principal("alice")?;

        leases.acquire(
            owner.clone(),
            ControlLeaseId::new(),
            None,
            MonotonicMillis::new(1),
            token,
        )?;
        assert!(leases.advance_time(MonotonicMillis::new(60_001))?);
        assert_eq!(leases.phase(), LeasePhase::Revoking);
        assert_eq!(
            leases.acquire(
                principal("bob")?,
                ControlLeaseId::new(),
                None,
                MonotonicMillis::new(60_001),
                token,
            ),
            Err(LeaseError::ResetRequired)
        );
        leases.begin_reset()?;
        leases.finish_reset()?;
        assert_eq!(leases.phase(), LeasePhase::Vacant);
        Ok(())
    }

    #[test]
    fn activity_never_implicitly_renews_expiry() -> Result<(), Box<dyn std::error::Error>> {
        let desktop_id = DesktopId::new();
        let fence = GenerationFence::new(desktop_id, DesktopGeneration::new());
        let token = fence.capture();
        let mut leases = LeaseMachine::new(desktop_id, token, LeasePolicy::default())?;
        let owner = principal("alice")?;
        let lease_id = ControlLeaseId::new();
        let original = leases.acquire(
            owner.clone(),
            lease_id,
            None,
            MonotonicMillis::new(100),
            token,
        )?;
        let active = leases.authorize(&owner, lease_id, MonotonicMillis::new(59_999), token)?;

        assert_eq!(active.expires_at, original.expires_at);
        assert_eq!(
            leases.authorize(&owner, lease_id, MonotonicMillis::new(60_100), token,),
            Err(LeaseError::Expired)
        );
        assert_eq!(leases.phase(), LeasePhase::Revoking);
        Ok(())
    }

    #[test]
    fn generation_change_revokes_and_fences() -> Result<(), Box<dyn std::error::Error>> {
        let desktop_id = DesktopId::new();
        let mut fence = GenerationFence::new(desktop_id, DesktopGeneration::new());
        let old = fence.capture();
        let mut leases = LeaseMachine::new(desktop_id, old, LeasePolicy::default())?;
        let owner = principal("alice")?;
        let lease_id = ControlLeaseId::new();
        leases.acquire(owner.clone(), lease_id, None, MonotonicMillis::new(0), old)?;
        let current = fence.rotate(DesktopGeneration::new())?;
        leases.rotate_generation(current)?;

        assert_eq!(leases.phase(), LeasePhase::Revoking);
        assert_eq!(
            leases.authorize(&owner, lease_id, MonotonicMillis::new(1), old),
            Err(LeaseError::StaleGeneration)
        );
        Ok(())
    }
}
